# -*- coding: utf-8 -*-
"""applyed_statitcs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlRbKbTf6CDa-YbpFxYVGDbLLM13K-CO
"""

# Creating Series from Array
import pandas as pd
import numpy as np
info = np.array(['p','a','n','d','a','s'])
a = pd.Series(info)
print(a)

# Create a Data Frame using list
import pandas as pd
#a list of strings
x=['Python','Pandas']
df = pd.DataFrame(x)
print(df)

import pandas as pd
import numpy as np
a = pd.Series(['Java','C',"C++",np.nan])
a.map({'Java':'Core','C':'Core1'})
a.map({'C++':'Core2'})

s =pd.Series(["a","b","c"],
name="vals")
s.to_frame()

import pandas as pd
import matplotlib.pyplot as plt
emp =['Parker','John','Smith','William']
id =[102,107,109,114]
emp_series =pd.Series(emp)
id_series = pd.Series(id)
frame ={'Emp':emp_series,'ID':id_series}
result =pd.DataFrame(frame)
print(result)

# create an empty DataFrame
import pandas as pd
df=pd.DataFrame()
print(df)

# Create a DataFrame using list
import pandas as pd
x=['Python','Pandas']
df=pd.DataFrame(x)
print(df)

# create a DataFrame from dict of ndarray/list
import pandas as pd
info={'ID':[101,102,103],'Department':['B.Sc','B.tech','M.tech']}
df=pd.DataFrame(info)
print (df)

# Create a DataFrame from Dict of Series:
import pandas as pd
info ={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
d1 = pd.DataFrame(info)
print(d1)

# In the above code, a dictinary named "info" consists of two Series with its respective index.
import