# -*- coding: utf-8 -*-
"""applyed_statitcs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlRbKbTf6CDa-YbpFxYVGDbLLM13K-CO
"""

# Creating Series from Array
import pandas as pd
import numpy as np
info = np.array(['p','a','n','d','a','s'])
a = pd.Series(info)
print(a)

# Create a Data Frame using list
import pandas as pd
#a list of strings
x=['Python','Pandas']
df = pd.DataFrame(x)
print(df)

import pandas as pd
import numpy as np
a = pd.Series(['Java','C',"C++",np.nan])
a.map({'Java':'Core','C':'Core1'})
a.map({'C++':'Core2'})

s =pd.Series(["a","b","c"],
name="vals")
s.to_frame()

import pandas as pd
import matplotlib.pyplot as plt
emp =['Parker','John','Smith','William']
id =[102,107,109,114]
emp_series =pd.Series(emp)
id_series = pd.Series(id)
frame ={'Emp':emp_series,'ID':id_series}
result =pd.DataFrame(frame)
print(result)

